### ISSUE TITLE
Client MAC address information

### ISSUE THREAD

**Issue by laurentandrian** [cisco-en-programmability/splunk-apps#11]
Are the clients MAC address collected with the Splunk add-on ?
I can't find it in the collected data in Splunk.

**Comment by wastorga** [comment]
Hi @laurentandrian 

We don't capture the Mac Address for Client Health dashboard, we only gather the general overall clienth health.

We do capture it for Compliance, Device Health, Issues and Security advisor dashboards.

**Comment by laurentandrian** [comment]
Hello,

Thank you for your answer. 
But could you clarify if the Client Mac address (i.e. a client device connected to a switch or an AP) is collected from DNAC using the splunk add on ?
Or it is only the MAC address of the network devices : switches, APs, routers ?

**Comment by wastorga** [comment]
@laurentandrian 

The inputs (of the mentioned dashboards) get their information from DNA Center's Network Devices API using the GET method [/dna/intent/api/v1/network-device](https://developer.cisco.com/docs/dna-center/#!cisco-dna-center-2-2-3-api-api-devices-get-device-list).

**Comment by laurentandrian** [comment]
So you are not getting anything from this method  
/dna/intent/api/v1/client-detail ?

**Comment by wastorga** [comment]
Correct, we are not getting data from that method (/dna/intent/api/v1/client-detail). 

For clients just from the /dna/intent/api/v1/client-health (Get overall client health) method.
