### ISSUE TITLE
Issues Query Filtering

### ISSUE THREAD

**Issue by phphasuk** [cisco-en-programmability/splunk-apps#12]
I have a question about the cisco_dnac_issue. I understand that the app issues and then query issue enrichment details, sites, network-device on every issues. I have many issues, around 300-500 issues in my DNAC. So the app sends too many queries to DNAC. If I would like to limit the number of query by only enabling the app to query issue but not the issue enrichment details, site, and network-device, Do you have any suggestion on how I should update the source code? or To add the filter based on the issue severity to limit the number of issues, what is the best way to edit the code? Can I edit the source code in $SPLUNK/etc/app/Splunk-TA-cisco-datacenter/bin?

I see that it is recommended to add the input logic to file input_module_cisco_dnac_issue.py. Should I put the filter into this "input_module_cisco_dnac_issue.py" file?

Appreciated.

 Thanks,
Phithakkit

**Comment by wastorga** [comment]
Hi @phphasuk 

Yes, the file to change would be `input_module_cisco_dnac_issue.py`, function `get_issues`. You would need to rewrite the `if issue_id: ...` code, the API call is done by function `dnac.issues.get_issue_enrichment_details` 

There are some fields that the `issue_item` (item of the general get has):

```python
issue_info[issue_id].update(
    {
        "IssueName": issue_item.get("name") or "",
        "IssueDeviceRole": issue_item.get("deviceRole") or "",
        "IssueAiDriven": issue_item.get("aiDriven") or "",
        "IssueClientMac": issue_item.get("clientMac") or "",
        "IssueCount": issue_item.get("issue_occurence_count") or "",
        "IssueStatus": issue_item.get("status") or "",
        "IssuePriority": issue_item.get("priority") or "",
        "IssueCategory": issue_item.get("category") or "",
    }
)
```

and others that are currently obtained using the enrichment details (see `simplify_issue` code)

1. IssueID
2. IssueSpecificCategory
3. IssueSpecificSource
4. IssueSpecificName
5. IssueSpecificEntity
6. IssueSpecificSeverity
7. IssueSpecificPriority
8. IssueSpecificSummary
9. IssueSpecificTimestamp
10. IssueSpecificDescription
11. IssueSpecificEntityValue

Note: Some of these fields are required for the dashboard of the Cisco DNA Center App for Splunk, search the field on the Splunk_CiscoDNACenter folder.

**Comment by phphasuk** [comment]
Hi @wastorga , 
Thank you so much for your suggestion. I will test it.

**Comment by wastorga** [comment]
Hi @phphasuk,
Can I help you with anything else?

If everything went well, feel free to close the ticket.
If no response is given, I will close due to inactivity on September 2nd.

**Comment by phphasuk** [comment]
Hi @wastorga ,

I think, We can close this case. Thank you so much for your suggestion.

**Comment by wastorga** [comment]
Hi @phphasuk

Great, glad I was able to help.
