### ISSUE TITLE
Splunk Cloud supporting for Splunk DNAC add-on App

### ISSUE THREAD

**Issue by phphasuk** [cisco-en-programmability/splunk-apps#15]
Hi Expert,

Does the Splunk DNAC add-on App support Splunk Cloud using IDM as the forwarder?

Thanks,
Phithakkit

**Comment by zapodeanu** [comment]
The current App versions are not Splunk Cloud Certified. We hope with the next version, targeted for May 2024 to re-certify for Splunk Cloud.

**Comment by phphasuk** [comment]
Thank you so much, Phithakkit
