### ISSUE TITLE
Integration DNAC with Splunk

### ISSUE THREAD

**Issue by SSimsima** [cisco-en-programmability/splunk-apps#7]
Hello Team, 

I'm not able to receive any data from DNAC.
I've installed the Splunk_CiscoDNACenter.spl first and then Splunk-TA-cisco-dnacenter.spl.
On Cisco DNA Center Add-on > Input: I've created the input with the DNAC VIP Management Address
On Configuration, I've created the account with DNAC credential.
DNAC and Splunk are reachable from DNAC management VIP (Cluster of 3 nodes)
Do I need to configure something on DNAC side? 

I'll really appreciate your support.

**Comment by zapodeanu** [comment]
Is your Splunk Enterprise server able to reach Cisco DNA Center?

**Comment by SSimsima** [comment]
Correct, from Splunk  I can reach the DNA Center.
Both  splunk and dna ( management interface) are in the same subnet.
Do I need to configure something on the DNAC?

Thank you for your help

**Comment by SSimsima** [comment]
Thank you for your email,
The issue was resolved.
Kind regards
